### ISSUE TITLE
Missing files despite install

### ISSUE THREAD

**Issue by leeburnell** [bonnv79/react-bootstrap-storybook#1]
After following the instructions in the readme - the story files for the Bootstrap components aren't present. 

How have you implemented the components as shown on https://bonnv79.github.io/react-bootstrap-storybook/?path=/story/storybook-introduction--page ?

**Comment by bonnv79** [comment]
hi @leeburnell,

I checked your problem and did a small demo on codesandbox.io, I found the library still working properly after installation. You can check out the demo at the link below.

Link: [https://codesandbox.io/s/react-bootstrap-storybook-yymqk2?file=/src/App.js](https://codesandbox.io/s/react-bootstrap-storybook-yymqk2?file=/src/App.js)

**Comment by byoung2** [comment]
@bonnv79 Do you have all the story files as shown in the demo? Are they in another repo?

**Comment by bonnv79** [comment]
hi @byoung2 ,
This library is built on react-bootstrap repo. Most of the demos are customizations of the components included in the react-bootstrap repo. The rest of the demos are taken from the react-bootstrap repo.

https://www.npmjs.com/package/react-bootstrap

**Comment by byoung2** [comment]
@bonnv79 thank you. I see the demos there, but not the story files. Am I missing something? I was hoping to have a local copy of all the story files like your demo site so I could modify and build on it
